[package]
name = "tui_document"
version = "0.9.21"
license = "MIT"
authors = ["David McFarland <dmcfarland8031@gmail.com>"]
description = "A Ratatui widget wrapping the Ropey crate."
documentation = "https://docs.rs/tui_document"
repository = "https://github.com/killrpenguin/tui_document"
categories = ["text-editors", "text-processing"]
keywords = ["tui", "editor", "input", "ratatui", "text-processing"]
exclude = [".gitignore"]
edition = "2024"

[dependencies]
ropey = "1.6.1"
ratatui = { version = "0.29.0", features = ["serde", "macros"] }
unicode-segmentation = "1.12.0"
unicode-width = "0.2.0"

[dev-dependencies]
insta = "1.43.1"
